name: Hourly Playlist Monitor

on:
  schedule:
    - cron: "*/10 * * * *"  # Every hour at minute 0
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write  # ✅ allow pushing to the repo

jobs:
  monitor-playlist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Monitor playlist for new tracks
        run: python main.py
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Commit and push updated tracking file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add last_playlist_track.txt
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update last playlist track [auto]"
            git push origin HEAD:${{ github.ref }}
          fi
